### ISSUE TITLE
Support for authentication w. token

### ISSUE THREAD

**Issue by GriffinSauce** [splitbee/notion-api-worker#1]
Hi, this package works well for my use case (grabbing data from a Notion table, nice and simple) but it would be nice to have auth support via the token.

The notion-api-agent repo has some docs on how to get your token:
https://github.com/dragonman225/notionapi-agent/blob/master/documentation/get-token/get-token.md

I've tried to add support for it but sadly [tiny-request-router](https://github.com/berstend/tiny-request-router) doesn't support headers or query params so I'd like to get your opinion first, Is it something you would like to add? And do you have thoughts about changing to a different router option?

**Comment by tobiaslins** [comment]
We just added support for that!
`tiny-request-router` doesn't limit us here. We just needed to add an additional param to the matched method: https://github.com/splitbee/notion-api-worker/blob/master/src/index.ts#L60

**Comment by GriffinSauce** [comment]
Ah great, cheers!
