### ISSUE TITLE
Image Access Denied

### ISSUE THREAD

**Issue by arnaudjnn** [splitbee/notion-api-worker#28]
I get Access Denied message for image block. How to access the URL? My notion is public.

https://s3-us-west-2.amazonaws.com/secure.notion-static.com/6b42051e-e390-4f74-a790-a9347a5adc65/1.jpg

**Comment by Tibfib** [comment]
I've been getting image errors lately too. Haven't made much progress in figuring out why. Anyone else?

**Comment by Tibfib** [comment]
Oh, here is a PR into react-notion to get it fixed. Has some info on what the cause is. https://github.com/splitbee/react-notion/pull/32

**Comment by tobiaslins** [comment]
Yes this was fixed within react-notion
https://github.com/splitbee/react-notion/pull/32
