### ISSUE TITLE
error: Route not found

### ISSUE THREAD

**Issue by lgs** [splitbee/notion-api-worker#29]
Calling whatever endpoint, like different page IDs, I always get a routing error:

```{"error":"Route not found!","routes":["/v1/page/:pageId","/v1/table/:pageId","/v1/user/:pageId"]}```

**Comment by aravindballa** [comment]
Can you tell the exact URL you are using? You might have missed mentioning the `endpoint`.

You should be looking at `https://notion-api.splitbee.io/v1/page/<page-ID>`

**Comment by BrandoZhang** [comment]
> Can you tell the exact URL you are using? You might have missed mentioning the `endpoint`.
> 
> You should be looking at `https://notion-api.splitbee.io/v1/page/<page-ID>`

I get the same error when visiting `https://notion-api.splitbee.io/`.

**Comment by tobiaslins** [comment]
As @aravindballa said you need to call the API with a path.

Eg `https://notion-api.splitbee.io/v1/page/<page-ID>`
