### ISSUE TITLE
Writing notion blocks?

### ISSUE THREAD

**Issue by jordanh** [splitbee/notion-api-worker#3]
Curious if you folks have experimented with writing data back to Notion? What does the format of a block look like? Markdown, a JSON schema? Something else?

**Comment by tobiaslins** [comment]
I took a short look at it and it's sadly not that easy to implement. They will hopefully release the official API soon that will cover this case!

**Comment by tobiaslins** [comment]
I'll close this issue for now.
We will let you know if there is any news on the official API
