### ISSUE TITLE
Feature Request: Coda.io api worker

### ISSUE THREAD

**Issue by sirpooya** [splitbee/notion-api-worker#35]
Guys @transitive-bullshit @tobiaslins Could this worker also work with Coda.io tables?

**Comment by transitive-bullshit** [comment]
Possibly, but the purpose of this project and `react-notion` is to focus specifically on using Notion as a CMS.

My suggestion would be to find or write a similar type of API proxy for Coda.io as a separate project.

**Comment by transitive-bullshit** [comment]
@sirpooya check out `notion-client` in https://github.com/NotionX/react-notion-x.

There's no reason why the core API abstraction needs to be in a CF worker. `notion-client` provides a normal JS / TS API wrapper that you can call from anywhere (node.js / CF worker / lambda / coda.io api worker / etc).
