### ISSUE TITLE
Notion's private API changed

### ISSUE THREAD

**Issue by transitive-bullshit** [splitbee/notion-api-worker#38]
They changed their API today. All `loadPageChunk` calls will fail as-is.

See fix here https://github.com/NotionX/react-notion-x/pull/39/files

Related: #27

**Comment by smsmsmsmin** [comment]
See fix pull request here : #39

**Comment by tobiaslins** [comment]
Thanks @transitive-bullshit @smsmsmsmin 

Deployed the worker already. It's working again :)

They may have changed this because of their performance issues they have lately!
