### ISSUE TITLE
Many blocks are missing from page response

### ISSUE THREAD

**Issue by dvdsgl** [splitbee/notion-api-worker#41]
After a recent update, many blocks are no longer returned for our pages. One page dropped 50-100 blocks from the end of the page.

In page [bc7f910ef23b421487ca21b959c67c49](https://notion-api.splitbee.io/v1/page/bc7f910ef23b421487ca21b959c67c49), block `771f85de-f188-46e6-90d6-9b2dd814ba10` is listed in the content of the page, but the block content is not actually included.

We noticed that by deleting early blocks on the actual Notion page, missing blocks can be fetched by the API — in other words, blocks at the end of the page are more likely to be missing.

**Comment by transitive-bullshit** [comment]
Hmmm, comparing https://www.notion.so/Copy-of-2020-Q4-bc7f910ef23b421487ca21b959c67c49 with https://react-notion-x-demo.transitivebullsh.it/bc7f910ef23b421487ca21b959c67c49, I'm not able to see any difference for the part of the document in question.

Have you tried using https://github.com/NotionX/react-notion-x?

See attached screenshot.

<img width="864" alt="Screen Shot 2021-03-07 at 10 38 59 AM" src="https://user-images.githubusercontent.com/552829/110245498-62a46c80-7f31-11eb-8c77-979eed7567fe.png">

**Comment by transitive-bullshit** [comment]
This probably has to do with `notion-api-worker` not fetching as many async blocks as `notion-client` does https://github.com/NotionX/react-notion-x/blob/master/packages/notion-client/src/notion-api.ts#L71

**Comment by dvdsgl** [comment]
Wow! NotionX looks awesome! Trying now 👍

**Comment by dvdsgl** [comment]
I confirmed that `notion-client` is fetching all of the blocks.

**Comment by JhumanJ** [comment]
Hello, any update on this?

**Comment by tobiaslins** [comment]
Hey @JhumanJ + @dvdsgl

We just merged this now, thanks @JhumanJ !
