### ISSUE TITLE
Getting AccessDenied on uploaded images

### ISSUE THREAD

**Issue by Utkarshbhimte** [splitbee/notion-api-worker#44]
I am getting this error when I am using images from my notion doc
![image](https://user-images.githubusercontent.com/13379773/114743651-7fbb2f00-9d6a-11eb-8d70-f667ccd1c358.png)

This is my `notionId`: `96defe8701444f0782cc9b428929c79a`

I am rendering the page content using `react-notion-x`, those are working fine but the image URLs I am getting from the payload are not working 

Would appreciate any help on this one 😊

**Comment by tobiaslins** [comment]
Hey!

I just checked with react-notion and it seems to work fine for us:
https://react-notion.com/96defe8701444f0782cc9b428929c79a

The URL needs to be signed by the client!

**Comment by Utkarshbhimte** [comment]
Hey, thanks, how exactly do you "sign" a URL here for images?
I am creating a custom integration here.

**Comment by tobiaslins** [comment]
@Utkarshbhimte 
https://github.com/splitbee/react-notion/blob/master/src/utils.ts#L46-L62

Try to prefix the URL you get from the worker with `https://www.notion.so/image/` and be sure to call `encodeURIComponent` on the URL

**Comment by Utkarshbhimte** [comment]
Thanks 😊
