### ISSUE TITLE
There is a phenomenon where the content of notion gets cut off when it gets longer.

### ISSUE THREAD

**Issue by kjh4357** [splitbee/notion-api-worker#51]
There is a phenomenon where the content of notion gets cut off when it gets longer.

**Comment by JhumanJ** [comment]
I also experienced this, I think it's the same issue described in #46 and #41.

`notion-client` of NotionX seems to have fixed that issue. https://github.com/NotionX/react-notion-x/blob/master/packages/notion-client/src/notion-api.ts#L71

**Comment by tobiaslins** [comment]
This just got published!
