### ISSUE TITLE
Cannot access preview of the the library

### ISSUE THREAD

**Issue by ACAVJW4H** [splitbee/notion-api-worker#6]
Hey many thanks for working on this project. I came across the project, looking for a way to make a meaningful backup of our notion knowledge repo. However the preview is not functioning at the moment.

`{"error":"Route not found!","routes":["/v1/page/:pageId","/v1/table/:pageId"," /v1/user/:pageId"]}`

**Comment by tobiaslins** [comment]
What route are you trying to access?
Can you further explain your issue?

**Comment by timolins** [comment]
I'm closing this issue. Let us know if you still have issues.
