### ISSUE TITLE
Issue query notion

### ISSUE THREAD

**Issue by thanhlmm** [splitbee/notion-api-worker#64]
https://notion-api.splitbee.io/v1/page/76715632-d151-400d-8eb6-e7f1cc15ad6f

This API throw error and Idk what is the problem?

https://cuthanh.notion.site/Morphling-dApp-Tham-gia-Binance-Launchpad-76715632d151400d8eb6e7f1cc15ad6f

**Comment by rylax** [comment]
Experiencing the same issue.

**Comment by thanhlmm** [comment]
The issue is due to the Cloudflare worker limit of 50 sub requests, and the pages is more than 50 block, that's why it fail.

I have to use `notion-client` and `react-notion-x` instead

**Comment by danielfalbo** [comment]
Why is that request calling more than 50 subrequests? How can we debug this?

**Comment by janniks** [comment]
I believe the 50 subrequests are being re-sent, because `syncRecordValues` if currently failing. Pages that don't require a `syncRecordValues` are fine. Testing experimental fix here: https://experimental.vue-notion.workers.dev

**Comment by janniks** [comment]
Potential fix: https://github.com/splitbee/notion-api-worker/pull/65

**Comment by janzheng** [comment]
@janniks wow that works! Thanks so for tracing and fixing the problem, @janniks!
I guess the API is shifting a lot, from the Collection change to this syncRecordValues change.

Also, if we have massive Notion pages we'll end up hitting 50 subrequest problem anyway — do you think it's worthwhile thinking about implementing a blockmap caching system on top of Workers KV or Durable Objects?

**Comment by janniks** [comment]
I think 50 subrequests will be enough for 99.9…% of pages. The endpoint can fetch many blocks at once and likely only needs few subrequests to fill up any missing blocks. The only problem might be blocks that include many recursively nested collections/similar (pretty unlikely to come up naturally). I believe the general logic is good enough.
